<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>      
    <TargetFramework>net10.0-android</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ExpandableLayout.Android</AssemblyName>
    <RootNamespace>ExpandableLayout.Android</RootNamespace>
    <PackageId>ExpandableLayout.Android</PackageId>
    <PackageProjectUrl>https://github.com/AlexeyBuryanov/ExpandableLayout.Android</PackageProjectUrl>
    <RepositoryUrl>https://github.com/AlexeyBuryanov/ExpandableLayout.Android</RepositoryUrl>
    <Description>Port for .NET 10.</Description>
    <Version>1.1.0</Version>
    <PackageVersion>1.1.0</PackageVersion>
    <Authors>Oleksii Burianov</Authors>
    <NeutralLanguage>en-US</NeutralLanguage>
    <PackageTags>net10-android;android;expandable layout</PackageTags>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>